name: 'Hello Github'
description: 'Render'
inputs:
  repository_url: # id of input
    description: 'Repository to render'
    required: true
    default: https://github.com/${{ github.repository }}.git
  source_branch:
    description: 'Branch to render'
    default: 'main'
    required: false
  target_branch_directory:
    description: 'Target Branch Directory'
    default: 'master'
    required: false
outputs:
  renderedPath:
    description: "Rendered Path"
    value: ${{ steps.output.outputs.renderedPath }}
runs:
  using: "composite"
  steps:
    - id: checkout
      shell: bash
      run: |
        git clone --depth 1 ${{ inputs.repository_url }} -b ${{ inputs.source_branch }} project

    - id: jobfile
      shell: bash
      run: |
        touch project/jobfile.json
        cat << EOF > project/jobfile.json
        {
            "Overrides_cfg": {
                "general": {
                    "release": "${{ inputs.target_branch_directory }}"
                },
                "html_theme_options": {
                    "docstypo3org": "yes"
                }
            }
        }
        EOF

    - id: render
      shell: bash
      run: |
        mkdir -p project/RenderedDocumentation
        docker run --rm --user=$(id -u):$(id -g) \
          -v $(pwd)/project:/PROJECT:ro \
          -v $(pwd)/project/RenderedDocumentation:/RESULT \
          t3docs/render-documentation makehtml \
            -c make_singlehtml 1 \
            -c "/ALL/Menu/mainmenu.sh makehtml -c replace_static_in_html 1 -c make_singlehtml 1 -c jobfile /PROJECT/jobfile.json"

    - id: output
      shell: bash
      run: |
        echo "::set-output name=renderedPath::project/RenderedDocumentation/"
