on:
  repository_dispatch:
    types: ['render']

jobs:
  hello_github:
    runs-on: ubuntu-latest
    name: Render Documentation
    steps:
      # until the action is published.
      - name: Checkout
        uses: actions/checkout@v2

      - name: Render Repository
        uses: ./actions/render/
        id: rendering
        with:
          repository_url: ${{ github.event.client_payload.repository_url }}
          source_branch: ${{ github.event.client_payload.source_branch }}
          target_branch_directory: ${{ github.event.client_payload.target_branch_directory }}

      - name: Publish archive with result
        uses: actions/upload-artifact@v1
        with:
          name: Rendered
          path: ${{ steps.rendering.outputs.renderedPath }}
